### ISSUE TITLE
Resending invoice use wrong locale

### ISSUE THREAD

**Issue by Gounlaf** [Sylius/InvoicingPlugin#81]
Hi,

In administration panel, when resending the invoice, the locale used is the one from the current logged user (administrator), and not the invoice locale.

I didn't investigate the code. I might do a PR (but don't know when)

**Comment by bartoszpietrzak1994** [comment]
Hello Gounlaf,

which version of InvoicingPlugin do you use in your project? I investigated the code and locale used to be taken from the current logged administrator but it was fixed in `0.3.1` version.

**Comment by Zales0123** [comment]
Hello Levis, did you check out a possible solution that @bartoszpietrzak1994 proposed? :)

**Comment by Gounlaf** [comment]
Hi,

Sorry, I've not checked yet. I will do soon.

**Comment by Gounlaf** [comment]
Hi @bartoszpietrzak1994, @Zales0123,

I was using (and still use) the latest tagged version 0.6.0.
I override the default provided template with mine. I didn't find any method to do so, so I reconfigure the service, injecting my template path

```yaml
    myapp.invoice.pdf_file_generator:
        class: Sylius\InvoicingPlugin\Generator\InvoicePdfFileGenerator
        decorates: Sylius\InvoicingPlugin\Generator\InvoicePdfFileGenerator
        arguments:
            - '@Sylius\InvoicingPlugin\Repository\InvoiceRepository'
            - '@sylius.repository.channel'
            - '@templating.engine.twig'
            - '@knp_snappy.pdf'
            - 'invoice/pdf.html.twig'
```

I first thank it was the problem, but returning to default configuration didn't fix the issue.

I'm using the default key provided in original template, translated with `trans`.
I've just changed html/css, nothing else =/

**Comment by bartoszpietrzak1994** [comment]
@Gounlaf I've seen that you have forked the InvoicingPlugin repository. Could you push your changes? It will be easier for me to propose a solution after looking at your code.

**Comment by bartoszpietrzak1994** [comment]
@Gounlaf I investigated the problem again and still am unable to find a possible issue :D Could you tell me how did you find out that the invoice is sent with the wrong locale?

**Comment by Gounlaf** [comment]
Since I don't have time (yet) to create a "test project" with all set, can I contact you privatly to give you some access?

**Comment by bartoszpietrzak1994** [comment]
Yup, feel free.

**Comment by Gounlaf** [comment]
@bartoszpietrzak1994 I don't find your e-mail on your profile ; mine is available ; can you send me yours please?

**Comment by bartoszpietrzak1994** [comment]
@Gounlaf I've just updated the email address on my profile - I wasn't aware of the fact that it was not displayed :( Should be fine now :)

**Comment by Gounlaf** [comment]
Well... It's really strange. It's not an issue anymore! (I've just said by e-mail I still have
It's a good news, but I have no idea about what's the issue.

I've just updated dependencies (I've not updated at least since 14 days), and there is no more problem.

I don't know if it's an environment issue (local/prod), a dependency related issue, cache... or if I was f*** high...

I'm really sorry for the inconvenience =/

It's time to close this issue!

Regards, and sorry again =/
